name: fdk
channels:
- pytorch
- defaults
dependencies:
- python>=3.7.3
- pytorch== 1.7.0
- torchvision==0.8.1
- jupyterlab
- pip>=20.1.1 
- pip:
  - opencv-python==4.3.*
  - Pillow>=7.1.2
  - transformers==3.0.2
  - matplotlib>=3.2.2
  - numpy==1.18.5
  - scikit-image==0.17.2
  - pyyaml>=5.1
